import Head from 'next/head';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import CardTodo from '@/components/ListTodo';
import { ProviderTodo } from '@/context';

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    if (!localStorage.getItem('userData')) router.push('/login');
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProviderTodo>
          <CardTodo />
        </ProviderTodo>
      </main>
    </>
  );
}
